# Generated by Django 5.2.1 on 2025-10-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0023_projecttypecosthistory_project_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='total_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total area in square meters', max_digits=10, null=True),
        ),
    ]
