# Generated by Django 5.2.1 on 2025-10-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0024_projectprofile_total_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='boq_division_subtotals',
            field=models.JSONField(blank=True, help_text='Cost subtotals by division from BOQ data', null=True),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='boq_project_info',
            field=models.JSONField(blank=True, help_text='Project information extracted from BOQ (floor area, etc.)', null=True),
        ),
    ]
