# Generated by Django 5.2.1 on 2025-10-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0025_add_boq_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectprofile',
            name='total_area',
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='floor_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Floor area in square meters', max_digits=10, null=True),
        ),
    ]
