# Generated by Django 5.2.1 on 2025-10-22 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('project_profiling', '0026_add_floor_area_and_boq_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='rfs_file',
            field=models.FileField(blank=True, help_text='Auto-generated Request for Supplier file', null=True, upload_to='rfs_files/'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='document_type',
            field=models.CharField(choices=[('CONTRACT', 'Contract Agreement'), ('PERMIT', 'Permit/License'), ('PROGRESS', 'Progress Report'), ('COSTING', 'Costing Proof'), ('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('TECHNICAL', 'Technical Drawing'), ('PHOTO', 'Project Photo'), ('QUOTATION', 'Supplier Quotation'), ('RFS', 'Request for Supplier'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='SupplierQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(help_text='Name of the supplier', max_length=200)),
                ('quotation_file', models.FileField(help_text='Uploaded quotation file (PDF or Excel)', upload_to='quotations/')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount quoted (can be manual or auto-calculated)', max_digits=15)),
                ('date_submitted', models.DateTimeField(auto_now_add=True, help_text='When this quotation was submitted')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current status of this quotation', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When this quotation was approved', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this quotation')),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved this quotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quotations', to='authentication.userprofile')),
                ('project', models.ForeignKey(help_text='Project this quotation is for', on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='project_profiling.projectprofile')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this quotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_quotations', to='authentication.userprofile')),
            ],
            options={
                'verbose_name': 'Supplier Quotation',
                'verbose_name_plural': 'Supplier Quotations',
                'ordering': ['-date_submitted'],
                'indexes': [models.Index(fields=['project', 'status'], name='project_pro_project_9cede5_idx'), models.Index(fields=['supplier_name'], name='project_pro_supplie_7e51fc_idx')],
            },
        ),
    ]
