# Generated by Django 5.2.1 on 2025-10-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('project_profiling', '0027_projectprofile_rfs_file_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='supplierquotation',
            name='project_pro_project_9cede5_idx',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='project',
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='project_id',
            field=models.PositiveIntegerField(default=1, help_text='Project ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='project_type',
            field=models.CharField(choices=[('profile', 'ProjectProfile'), ('staging', 'ProjectStaging')], default=1, help_text='Type of project (profile or staging)', max_length=20),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='supplierquotation',
            index=models.Index(fields=['project_id', 'project_type', 'status'], name='project_pro_project_95db8d_idx'),
        ),
    ]
