# Generated by Django 5.2.1 on 2025-10-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0028_remove_supplierquotation_project_pro_project_9cede5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierquotation',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount quoted (can be manual or auto-calculated)', max_digits=15, null=True),
        ),
    ]
