# Generated by Django 5.2.1 on 2025-10-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0029_alter_supplierquotation_total_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobilizationCost',
        ),
    ]
