# Generated by Django 5.2.1 on 2025-10-22 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('materials_equipment', '0001_initial'),
        ('project_profiling', '0030_remove_mobilization_cost_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpricemonitoring',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this price record is associated with (for BOQ/Quotation types)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='project_profiling.projectprofile'),
        ),
        migrations.AlterField(
            model_name='materialpricemonitoring',
            name='supplier_type',
            field=models.CharField(choices=[('REG', 'Regular Supplier'), ('RND', 'Random Supplier'), ('BTH', 'Both'), ('BOQ', 'BOQ Estimate'), ('QUO', 'Project Quotation')], max_length=3),
        ),
        migrations.AlterField(
            model_name='projectmaterial',
            name='supplier_type',
            field=models.CharField(choices=[('REG', 'Regular Supplier'), ('RND', 'Random Supplier'), ('BTH', 'Both'), ('BOQ', 'BOQ Estimate'), ('QUO', 'Project Quotation')], max_length=3),
        ),
        migrations.CreateModel(
            name='ProjectMaterialExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('BOQ', 'BOQ File'), ('QUOTATION', 'Quotation File')], max_length=10)),
                ('source_file', models.CharField(help_text='Original file name', max_length=500)),
                ('extraction_date', models.DateTimeField(auto_now_add=True)),
                ('materials_count', models.PositiveIntegerField(default=0)),
                ('equipment_count', models.PositiveIntegerField(default=0)),
                ('mobilization_count', models.PositiveIntegerField(default=0)),
                ('total_extracted_value', models.DecimalField(decimal_places=2, default=0, help_text='Total value of extracted items', max_digits=15)),
                ('extraction_notes', models.TextField(blank=True, null=True)),
                ('extracted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extractions', to='authentication.userprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_extractions', to='project_profiling.projectprofile')),
            ],
            options={
                'ordering': ['-extraction_date'],
                'indexes': [models.Index(fields=['project', 'source_type'], name='materials_e_project_aa102f_idx'), models.Index(fields=['extraction_date'], name='materials_e_extract_904273_idx')],
            },
        ),
    ]
