# Generated by Django 5.2.1 on 2025-10-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_equipment', '0002_add_price_monitoring_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='source',
            field=models.CharField(blank=True, help_text='Source of material: BOQ, QUOTATION, MANUAL', max_length=20),
        ),
    ]
